- name: restart apache2
  service: name=apache2 state=restarted
  become: true

- name: reload apache2
  service: name=apache2 state=reloaded
  become: true

- name: restart php7-fpm
  service: name=php7.2-fpm state=restarted
  become: true

- name: reload php7-fpm
  service: name=php7.2-fpm state=reloaded
  become: true
